sudo : required
services:
  - docker

before_install:
  - docker build -t dbodnya/docker-react -f Dockerfile.dev .

script:
  - docker run dbodnya/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-docker"
  env: "ReactDocker-env"
  bucket_name: "arn:aws:s3:::elasticbeanstalk-us-east-2-003828950992"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
